# Generated by Django 3.0 on 2023-07-05 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230705_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
