# Generated by Django 4.2.3 on 2023-07-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_in_api',
            field=models.BooleanField(default=True),
        ),
    ]
